repositories:
  remote:
   - https://stocksoftware.jfrog.io/stocksoftware/maven2
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.jfrog.io/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.17

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1

  braincheck_core: org.realityforge.braincheck:braincheck-core:jar:1.31.0
  braincheck_testng: org.realityforge.braincheck:braincheck-testng:jar:1.30.0

  grim_annotations: org.realityforge.grim:grim-annotations:jar:0.05
  grim_processor: org.realityforge.grim:grim-processor:jar:0.05

  gwt_user: com.google.gwt:gwt-user:jar:2.9.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.9.0

  jsinterop_annotations: com.google.jsinterop:jsinterop-annotations:jar:2.0.0

  jsinterop_base: com.google.jsinterop:base:jar:1.0.0

  javax_json: org.glassfish:javax.json:jar:1.1

  javapoet: com.squareup:javapoet:jar:1.13.0
  guava: com.google.guava:guava:jar:27.1-jre
  failureaccess: com.google.guava:failureaccess:jar:1.0.1

  proton_core: org.realityforge.proton:proton-core:jar:0.51
  proton_qa: org.realityforge.proton:proton-qa:jar:0.51

  #test deps
  compile_testing: com.google.testing.compile:compile-testing:jar:0.18-rf
  truth: com.google.truth:truth:jar:0.45
  junit: junit:junit:jar:4.12
  hamcrest_core: org.hamcrest:hamcrest-core:jar:1.3

  shade_task: org.realityforge.ant.shade:ant-shade-task:jar:0.1

  jsonassert: org.skyscreamer:jsonassert:jar:1.5.0
  android_json: com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1
